GAME_TITLE = "Ping Pong"
GAME_FPS = 60
GAME_SCREEN_WIDTH = 500
GAME_SCREEN_HEIGHT = 550
GAME_BG_CLR = (0, 0, 0)
GAME_OBJ_CLR = (255, 255, 255)
SCREEN_DIV = [(0, GAME_SCREEN_HEIGHT // 2), (GAME_SCREEN_WIDTH, GAME_SCREEN_HEIGHT // 2)]

FONT_NAME = "arial"
FONT_SIZE = 20

PAD_WIDTH = GAME_SCREEN_WIDTH // 8
PAD_HEIGHT = 5
PAD_SPEED = 10

PAD_POSITION_DIFFERENCE = 40
PLAYER_PAD_POSITION = GAME_SCREEN_HEIGHT - PAD_POSITION_DIFFERENCE
BOT_PAD_POSITION = PAD_POSITION_DIFFERENCE
PLAYER_SCORE_POSITION = (10, GAME_SCREEN_HEIGHT // 2 + 20)
BOT_SCORE_POSITION = (10, GAME_SCREEN_HEIGHT // 2 - FONT_SIZE - 20)
