GAME_TITLE = "Ping Pong"
GAME_FPS = 60
GAME_SCREEN_WIDTH = 500
GAME_SCREEN_HEIGHT = 550
GAME_BG_CLR = (0, 0, 0)
GAME_OBJ_CLR = (255, 255, 255)
SCREEN_DIV = [(0, GAME_SCREEN_HEIGHT // 2), (GAME_SCREEN_WIDTH, GAME_SCREEN_HEIGHT // 2)]

PAD_WIDTH = GAME_SCREEN_WIDTH // 10
PAD_HEIGHT = 5

